### ISSUE TITLE
Rails 5 Not compatible? 

### ISSUE THREAD

**Issue by chevinbrown** [misopeso/google-webfonts-rails#4]
`google-webfonts-rails-0.0.4/lib/google-webfonts/rails/helpers.rb:7:in`block in module:Helpers': undefined method `helper_method' for ActionController::API:Class (NoMethodError)`

Any idea how to remedy for rails 5?

**Comment by n-rodriguez** [comment]
Hi! Got the same issue here :( Can you please merge https://github.com/misopeso/google-webfonts-rails/pull/2

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by chevinbrown** [comment]
@n-rodriguez, no updates that I know of...

**Comment by n-rodriguez** [comment]
@misopeso hi! this issue can be closed. Thank you!
